import { nanoid } from "nanoid";
import { sectionIds } from "../../miscMappings";

export const sectionParticipations = {
	id: sectionIds.sectionParticipations,
	showSection: true,
	heading: "Events And Participations",
	headingStyle: {},
	elements: [
		{
			id: nanoid(),
			eventName: "ASME Formula Balloon",
			labelTag: "First Runner Up",
			badgeClass: "HonorLabel_gold",
			labelTagNeeded: true,
			imgSource: "/web/images/events/formula_balloon.jpg",
			imgAlt: "Formula Balloon",
			style: { left: "-35%", top: "3%" },
		},
		{
			id: nanoid(),
			eventName: "ASME Mechanical Conference",
			labelTag: "Winner",
			labelClassName: "winner",
			badgeClass: "HonorLabel_gold",
			imgSource: "/web/images/events/mech_conf.jpg",
			imgAlt: "ASME Mechanical Conference",
		},
		{
			id: nanoid(),
			eventName: "ASME Reverse Engineering",
			labelTag: "Winner",
			labelTagNeeded: true,
			badgeClass: "HonorLabel_gold",
			imgSource: "/web/images/events/reverse_engineering.jpg",
			imgAlt: "ASME Reverse Engineering",
		},
		{
			id: nanoid(),
			eventName: "Dover Hackathon",
			labelTagNeeded: false,
			labelTag: "Participant",
			imgSource: "/web/images/events/formula_balloon.jpg",
			imgAlt: "ASME Reverse Engineering",
		},
		{
			id: nanoid(),
			eventName: "SEDS Astra Hack",
			labelTagNeeded: false,
			labelTag: "Participant",
			imgSource: "/web/images/events/formula_balloon.jpg",
			imgAlt: "ASME Reverse Engineering",
		},
		{
			id: nanoid(),
			eventName: "Design to Print",
			labelTagNeeded: false,
			labelTag: "Participant",
			imgSource: "/web/images/events/formula_balloon.jpg",
			imgAlt: "ASME Reverse Engineering",
		},
		{
			id: nanoid(),
			eventName: "Select Makeathon",
			labelTag: "Top 10 Qualifier",
			labelTagNeeded: true,
			badgeClass: "HonorLabel_silver",
			imgSource: "/web/images/events/formula_balloon.jpg",
			imgAlt: "ASME Reverse Engineering",
			style: { left: "-35%", top: "3%" },
		},
		{
			id: nanoid(),
			eventName: "Indian Rover Challenge 2018",
			labelTag: "Event Co-ordinator",
			labelTagNeeded: true,
			badgeClass: "HonorLabel_brown",
			imgSource: "/web/images/events/formula_balloon.jpg",
			imgAlt: "ASME Reverse Engineering",
			style: { left: "-35%", top: "7%" },
		},
		{
			id: nanoid(),
			eventName: "Indian Rover Challenge 2019",
			labelTag: "4th Rank (Global)",
			labelTagNeeded: true,
			badgeClass: "HonorLabel_silver",
			imgSource: "/web/images/events/irc2019.jpg",
			imgAlt: "ASME Reverse Engineering",
			style: { left: "-35%", top: "7%" },
		},
		{
			id: nanoid(),
			eventName: "ASME eFest",
			labelTagNeeded: false,
			labelTag: "Participant",
			imgSource: "/web/images/events/efest_asme.jpg",
			imgAlt: "ASME eFest Asia Pacific 2017",
		},
	],
};
